# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
   # branches: [ "main" ] # wir wollen nicht, dass diese Action bei jedem Push ausgeführt wird
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: Set up JDK 17 ##  wurde bei Dominic ohne, wie folgt generiert ...
    - name: Set up JDK   
      uses: actions/setup-java@v4
      with:
        java-version: '21' ## Anpassung an unsere aktuelle Java-Version.
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml ## Stellt sicher, dass der gesamte Build-Prozess einschließlich Tests durchgeführt wird.

## kann gelöscht werden
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
     # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
